services:
    node:
        build:
            context: .
            dockerfile: ./Dockerfile
        tty: true
        ports:
            - "3000:3000"
            - "5173:5173"
            - "4173:4173"
        working_dir: /var/www
        volumes:
            - ../www:/var/www
